# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# ---------------------------------------------------------

# Template for publishing test result report
parameters:
- name: py_version
  type: string

steps:
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' 
    testResultsFiles: 'junit/*.xml' 
    searchFolder: $(Build.SourcesDirectory)
    testRunTitle: $(Agent.OS) py$(py_version) Build
    buildPlatform: $(Agent.OS)
  condition: always() # Always publish test results
  displayName: 'Publish test report'